<?php
/**
 * Created by PhpStorm.
 * User: hilbr
 * Date: 25.03.2020
 * Time: 10:14
 */

namespace common\models;

use yii\helpers\Json;

class Question
{
    public static function imagePathsForTest()
    {
        $paths = [
            1 => [
                'question' => 'img/exos/ex1.png',
                'a' => 'img/exos/ex1_a.png',
                'b' => 'img/exos/ex1_b.png',
                'c' => 'img/exos/ex1_c.png',
                'd' => 'img/exos/ex1_d.png',
                'e' => 'img/exos/ex1_e.png',
                'f' => 'img/exos/ex1_f.png',
            ],
            2 => [
                'question' => 'img/exos/ex2.png',
                'a' => 'img/exos/ex2_a.png',
                'b' => 'img/exos/ex2_b.png',
                'c' => 'img/exos/ex2_c.png',
                'd' => 'img/exos/ex2_d.png',
                'e' => 'img/exos/ex2_e.png',
                'f' => 'img/exos/ex2_f.png',
            ],
            3 => [
                'question' => 'img/exos/ex3.png',
                'a' => 'img/exos/ex3_a.png',
                'b' => 'img/exos/ex3_b.png',
                'c' => 'img/exos/ex3_c.png',
                'd' => 'img/exos/ex3_d.png',
                'e' => 'img/exos/ex3_e.png',
                'f' => 'img/exos/ex3_f.png',
            ],
            4 => [
                'question' => 'img/exos/ex4.png',
                'a' => 'img/exos/ex4_a.png',
                'b' => 'img/exos/ex4_b.png',
                'c' => 'img/exos/ex4_c.png',
                'd' => 'img/exos/ex4_d.png',
                'e' => 'img/exos/ex4_e.png',
                'f' => 'img/exos/ex4_f.png',
            ],
            5 => [
                'question' => 'img/exos/ex5.png',
                'a' => 'img/exos/ex5_a.png',
                'b' => 'img/exos/ex5_b.png',
                'c' => 'img/exos/ex5_c.png',
                'd' => 'img/exos/ex5_d.png',
                'e' => 'img/exos/ex5_e.png',
                'f' => 'img/exos/ex5_f.png',
            ],
            6 => [
                'question' => 'img/exos/ex6.png',
                'a' => 'img/exos/ex6_a.png',
                'b' => 'img/exos/ex6_b.png',
                'c' => 'img/exos/ex6_c.png',
                'd' => 'img/exos/ex6_d.png',
                'e' => 'img/exos/ex6_e.png',
                'f' => 'img/exos/ex6_f.png',
            ],
            7 => [
                'question' => 'img/exos/ex7.png',
                'a' => 'img/exos/ex7_a.png',
                'b' => 'img/exos/ex7_b.png',
                'c' => 'img/exos/ex7_c.png',
                'd' => 'img/exos/ex7_d.png',
                'e' => 'img/exos/ex7_e.png',
                'f' => 'img/exos/ex7_f.png',
            ],
            8 => [
                'question' => 'img/exos/ex8.png',
                'a' => 'img/exos/ex8_a.png',
                'b' => 'img/exos/ex8_b.png',
                'c' => 'img/exos/ex8_c.png',
                'd' => 'img/exos/ex8_d.png',
                'e' => 'img/exos/ex8_e.png',
                'f' => 'img/exos/ex8_f.png',
            ],
            9 => [
                'question' => 'img/exos/ex9.png',
                'a' => 'img/exos/ex9_a.png',
                'b' => 'img/exos/ex9_b.png',
                'c' => 'img/exos/ex9_c.png',
                'd' => 'img/exos/ex9_d.png',
                'e' => 'img/exos/ex9_e.png',
                'f' => 'img/exos/ex9_f.png',
            ],
            10 => [
                'question' => 'img/exos/ex10.png',
                'a' => 'img/exos/ex10_a.png',
                'b' => 'img/exos/ex10_b.png',
                'c' => 'img/exos/ex10_c.png',
                'd' => 'img/exos/ex10_d.png',
                'e' => 'img/exos/ex10_e.png',
                'f' => 'img/exos/ex10_f.png',
            ],
            11 => [
                'question' => 'img/exos/ex11.png',
                'a' => 'img/exos/ex11_a.png',
                'b' => 'img/exos/ex11_b.png',
                'c' => 'img/exos/ex11_c.png',
                'd' => 'img/exos/ex11_d.png',
                'e' => 'img/exos/ex11_e.png',
                'f' => 'img/exos/ex11_f.png',
            ],
            12 => [
                'question' => 'img/exos/ex12.png',
                'a' => 'img/exos/ex12_a.png',
                'b' => 'img/exos/ex12_b.png',
                'c' => 'img/exos/ex12_c.png',
                'd' => 'img/exos/ex12_d.png',
                'e' => 'img/exos/ex12_e.png',
                'f' => 'img/exos/ex12_f.png',
            ],
            13 => [
                'question' => 'img/exos/ex13.png',
                'a' => 'img/exos/ex13_a.png',
                'b' => 'img/exos/ex13_b.png',
                'c' => 'img/exos/ex13_c.png',
                'd' => 'img/exos/ex13_d.png',
                'e' => 'img/exos/ex13_e.png',
                'f' => 'img/exos/ex13_f.png',
            ],
            14 => [
                'question' => 'img/exos/ex14.png',
                'a' => 'img/exos/ex14_a.png',
                'b' => 'img/exos/ex14_b.png',
                'c' => 'img/exos/ex14_c.png',
                'd' => 'img/exos/ex14_d.png',
                'e' => 'img/exos/ex14_e.png',
                'f' => 'img/exos/ex14_f.png',
            ],
            15 => [
                'question' => 'img/exos/ex15.png',
                'a' => 'img/exos/ex15_a.png',
                'b' => 'img/exos/ex15_b.png',
                'c' => 'img/exos/ex15_c.png',
                'd' => 'img/exos/ex15_d.png',
                'e' => 'img/exos/ex15_e.png',
                'f' => 'img/exos/ex15_f.png',
            ],
            16 => [
                'question' => 'img/exos/ex16.png',
                'a' => 'img/exos/ex16_a.png',
                'b' => 'img/exos/ex16_b.png',
                'c' => 'img/exos/ex16_c.png',
                'd' => 'img/exos/ex16_d.png',
                'e' => 'img/exos/ex16_e.png',
                'f' => 'img/exos/ex16_f.png',
            ],
            17 => [
                'question' => 'img/exos/ex17.png',
                'a' => 'img/exos/ex17_a.png',
                'b' => 'img/exos/ex17_b.png',
                'c' => 'img/exos/ex17_c.png',
                'd' => 'img/exos/ex17_d.png',
                'e' => 'img/exos/ex17_e.png',
                'f' => 'img/exos/ex17_f.png',
            ],
            18 => [
                'question' => 'img/exos/ex18.png',
                'a' => 'img/exos/ex18_a.png',
                'b' => 'img/exos/ex18_b.png',
                'c' => 'img/exos/ex18_c.png',
                'd' => 'img/exos/ex18_d.png',
                'e' => 'img/exos/ex18_e.png',
                'f' => 'img/exos/ex18_f.png',
            ],
            19 => [
                'question' => 'img/exos/ex19.png',
                'a' => 'img/exos/ex19_a.png',
                'b' => 'img/exos/ex19_b.png',
                'c' => 'img/exos/ex19_c.png',
                'd' => 'img/exos/ex19_d.png',
                'e' => 'img/exos/ex19_e.png',
                'f' => 'img/exos/ex19_f.png',
            ],
            20 => [
                'question' => 'img/exos/ex20.png',
                'a' => 'img/exos/ex20_a.png',
                'b' => 'img/exos/ex20_b.png',
                'c' => 'img/exos/ex20_c.png',
                'd' => 'img/exos/ex20_d.png',
                'e' => 'img/exos/ex20_e.png',
                'f' => 'img/exos/ex20_f.png',
            ],
            21 => [
                'question' => 'img/exos/ex21.png',
                'a' => 'img/exos/ex21_a.png',
                'b' => 'img/exos/ex21_b.png',
                'c' => 'img/exos/ex21_c.png',
                'd' => 'img/exos/ex21_d.png',
                'e' => 'img/exos/ex21_e.png',
                'f' => 'img/exos/ex21_f.png',
            ],
            22 => [
                'question' => 'img/exos/ex22.png',
                'a' => 'img/exos/ex22_a.png',
                'b' => 'img/exos/ex22_b.png',
                'c' => 'img/exos/ex22_c.png',
                'd' => 'img/exos/ex22_d.png',
                'e' => 'img/exos/ex22_e.png',
                'f' => 'img/exos/ex22_f.png',
            ],
            23 => [
                'question' => 'img/exos/ex23.png',
                'a' => 'img/exos/ex23_a.png',
                'b' => 'img/exos/ex23_b.png',
                'c' => 'img/exos/ex23_c.png',
                'd' => 'img/exos/ex23_d.png',
                'e' => 'img/exos/ex23_e.png',
                'f' => 'img/exos/ex23_f.png',
            ],
            24 => [
                'question' => 'img/exos/ex24.png',
                'a' => 'img/exos/ex24_a.png',
                'b' => 'img/exos/ex24_b.png',
                'c' => 'img/exos/ex24_c.png',
                'd' => 'img/exos/ex24_d.png',
                'e' => 'img/exos/ex24_e.png',
                'f' => 'img/exos/ex24_f.png',
            ],
            25 => [
                'question' => 'img/exos/ex25.png',
                'a' => 'img/exos/ex25_a.png',
                'b' => 'img/exos/ex25_b.png',
                'c' => 'img/exos/ex25_c.png',
                'd' => 'img/exos/ex25_d.png',
                'e' => 'img/exos/ex25_e.png',
                'f' => 'img/exos/ex25_f.png',
            ],
            26 => [
                'question' => 'img/exos/ex26.png',
                'a' => 'img/exos/ex26_a.png',
                'b' => 'img/exos/ex26_b.png',
                'c' => 'img/exos/ex26_c.png',
                'd' => 'img/exos/ex26_d.png',
                'e' => 'img/exos/ex26_e.png',
                'f' => 'img/exos/ex26_f.png',
            ],
            27 => [
                'question' => 'img/exos/ex27.png',
                'a' => 'img/exos/ex27_a.png',
                'b' => 'img/exos/ex27_b.png',
                'c' => 'img/exos/ex27_c.png',
                'd' => 'img/exos/ex27_d.png',
                'e' => 'img/exos/ex27_e.png',
                'f' => 'img/exos/ex27_f.png',
            ],
            28 => [
                'question' => 'img/exos/ex28.png',
                'a' => 'img/exos/ex28_a.png',
                'b' => 'img/exos/ex28_b.png',
                'c' => 'img/exos/ex28_c.png',
                'd' => 'img/exos/ex28_d.png',
                'e' => 'img/exos/ex28_e.png',
                'f' => 'img/exos/ex28_f.png',
            ],
            29 => [
                'question' => 'img/exos/ex29.png',
                'a' => 'img/exos/ex29_a.png',
                'b' => 'img/exos/ex29_b.png',
                'c' => 'img/exos/ex29_c.png',
                'd' => 'img/exos/ex29_d.png',
                'e' => 'img/exos/ex29_e.png',
                'f' => 'img/exos/ex29_f.png',
            ],
            30 => [
                'question' => 'img/exos/ex30.png',
                'a' => 'img/exos/ex30_a.png',
                'b' => 'img/exos/ex30_b.png',
                'c' => 'img/exos/ex30_c.png',
                'd' => 'img/exos/ex30_d.png',
                'e' => 'img/exos/ex30_e.png',
                'f' => 'img/exos/ex30_f.png',
            ],
            31 => [
                'question' => 'img/exos/ex31.png',
                'a' => 'img/exos/ex31_a.png',
                'b' => 'img/exos/ex31_b.png',
                'c' => 'img/exos/ex31_c.png',
                'd' => 'img/exos/ex31_d.png',
                'e' => 'img/exos/ex31_e.png',
                'f' => 'img/exos/ex31_f.png',
            ],
            32 => [
                'question' => 'img/exos/ex32.png',
                'a' => 'img/exos/ex32_a.png',
                'b' => 'img/exos/ex32_b.png',
                'c' => 'img/exos/ex32_c.png',
                'd' => 'img/exos/ex32_d.png',
                'e' => 'img/exos/ex32_e.png',
                'f' => 'img/exos/ex32_f.png',
            ],
            33 => [
                'question' => 'img/exos/ex33.png',
                'a' => 'img/exos/ex33_a.png',
                'b' => 'img/exos/ex33_b.png',
                'c' => 'img/exos/ex33_c.png',
                'd' => 'img/exos/ex33_d.png',
                'e' => 'img/exos/ex33_e.png',
                'f' => 'img/exos/ex33_f.png',
            ],
            34 => [
                'question' => 'img/exos/ex34.png',
                'a' => 'img/exos/ex34_a.png',
                'b' => 'img/exos/ex34_b.png',
                'c' => 'img/exos/ex34_c.png',
                'd' => 'img/exos/ex34_d.png',
                'e' => 'img/exos/ex34_e.png',
                'f' => 'img/exos/ex34_f.png',
            ],
            35 => [
                'question' => 'img/exos/ex35.png',
                'a' => 'img/exos/ex35_a.png',
                'b' => 'img/exos/ex35_b.png',
                'c' => 'img/exos/ex35_c.png',
                'd' => 'img/exos/ex35_d.png',
                'e' => 'img/exos/ex35_e.png',
                'f' => 'img/exos/ex35_f.png',
            ],
            36 => [
                'question' => 'img/exos/ex36.png',
                'a' => 'img/exos/ex36_a.png',
                'b' => 'img/exos/ex36_b.png',
                'c' => 'img/exos/ex36_c.png',
                'd' => 'img/exos/ex36_d.png',
                'e' => 'img/exos/ex36_e.png',
                'f' => 'img/exos/ex36_f.png',
            ],
            37 => [
                'question' => 'img/exos/ex37.png',
                'a' => 'img/exos/ex37_a.png',
                'b' => 'img/exos/ex37_b.png',
                'c' => 'img/exos/ex37_c.png',
                'd' => 'img/exos/ex37_d.png',
                'e' => 'img/exos/ex37_e.png',
                'f' => 'img/exos/ex37_f.png',
            ],
            38 => [
                'question' => 'img/exos/ex38.png',
                'a' => 'img/exos/ex38_a.png',
                'b' => 'img/exos/ex38_b.png',
                'c' => 'img/exos/ex38_c.png',
                'd' => 'img/exos/ex38_d.png',
                'e' => 'img/exos/ex38_e.png',
                'f' => 'img/exos/ex38_f.png',
            ],
            39 => [
                'question' => 'img/exos/ex39.png',
                'a' => 'img/exos/ex39_a.png',
                'b' => 'img/exos/ex39_b.png',
                'c' => 'img/exos/ex39_c.png',
                'd' => 'img/exos/ex39_d.png',
                'e' => 'img/exos/ex39_e.png',
                'f' => 'img/exos/ex39_f.png',
            ],
            40 => [
                'question' => 'img/exos/ex40.png',
                'a' => 'img/exos/ex40_a.png',
                'b' => 'img/exos/ex40_b.png',
                'c' => 'img/exos/ex40_c.png',
                'd' => 'img/exos/ex40_d.png',
                'e' => 'img/exos/ex40_e.png',
                'f' => 'img/exos/ex40_f.png',
            ],
        ];

        return Json::encode($paths);
    }
}