<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => '"{attribute}" должен содержать валидный JSON',
    'Active' => 'Активно',
    'API access token' => 'Токен доступа к API',
    'Article ID' => 'ID Статьи',
    'Article View' => 'Шаблон статьи',
    'Author' => 'Автор',
    'Base URL' => 'Базовый URL',
    'Base Url' => 'Базовый Url',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID карусели',
    'Category' => 'Категория',
    'Comment' => 'Комментарий',
    'Component' => 'Компонент',
    'Config' => 'Настройки',
    'Created At' => 'Создано',
    'Created at' => 'Создано',
    'Deleted' => 'Удалено',
    'Down to maintenance.' => 'Закрыто на обслуживание.',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Expire At' => 'Истекает',
    'File Type' => 'Тип файла',
    'Firstname' => 'Имя',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Key' => 'Ключ',
    'Last login' => 'Последний вход',
    'Lastname' => 'Фамилия',
    'Locale' => 'Локаль',
    'Middlename' => 'Отчество',
    'Name' => 'Имя',
    'Not Active' => 'Неактивно',
    'Order' => 'Порядок',
    'Page View' => 'Шаблон страницы',
    'Parent Category' => 'Родительская категория',
    'Password' => 'Пароль',
    'Path' => 'Путь',
    'Picture' => 'Аватар',
    'Published' => 'Опубликовано',
    'Published At' => 'Дата публикации',
    'Roles' => 'Роли',
    'Size' => 'Размер',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Thumbnail' => 'Эскиз изображения',
    'Title' => 'Название',
    'Token' => 'Токен',
    'Type' => 'Тип',
    'Updated At' => 'Обновлено',
    'Updated at' => 'Последнее обновление',
    'Updater' => 'Обновивший',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'ID пользователя',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'No diploma' => 'Без диплома',
    'High School' => 'Диплом средней школы',
    '2 years of higher education' => '2 года высшего образования',
    '3 years of higher education' => '3 года высшего образования',
    '4 years of higher education' => '4 года высшего образования',
    '5 years of higher education' => '5 года высшего образования',
    'more 5 years of higher education' => 'Больше 5 лет высшего образования',
    'Agriculture' => 'Сельскохозяйственная школа',
    'Architecture and urbanism' => 'Архитектура и планирование',
    'Art and design' => 'Искусство и дизайн',
    'Commercial and management' => 'Торговля и управление',
    'Education' => 'Образование',
    'Engineering and technology' => 'Техника и технологии',
    'Geography and geology' => 'География и геология',
    'Letters and culture' => 'Литература и культура',
    'Languages and philology' => 'Языки и филология',
    'Law' => 'Право',
    'Math and Computer Science' => 'Математика и ИТ',
    'Medical sciences' => 'Медицинские науки',
    'Natural Sciences' => 'Естественные науки',
    'Social sciences' => 'Социальные науки',
    'Communication and information' => 'Коммуникация и информация',
    'Send me a link with my result' => 'Отправьте мне ссылку с моим результатом',
    'Enter the email address you provided to receive the result' => 'Введите адрес электронной почты, который вы указали для получения результата',
];
